# Generated by Django 4.2.11 on 2024-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='colaborador',
            new_name='colaborador_avaliado',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='turno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
