# Generated by Django 5.0.7 on 2024-07-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='pergunta',
        ),
    ]
