# Generated by Django 5.0.7 on 2024-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(max_length=100),
        ),
    ]
