# Generated by Django 5.0.7 on 2024-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_remove_avaliacao_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.TextField(max_length=100),
        ),
    ]
