# Generated by Django 5.0.7 on 2024-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_remove_colaborador_cargo_alter_colaborador_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
