# Generated by Django 4.2.11 on 2024-07-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_rename_colaborador_avaliacao_colaborador_avaliado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colab.turno'),
        ),
    ]
