# Generated by Django 5.0.7 on 2024-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_turno_alter_colaborador_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
