# Generated by Django 5.0.7 on 2024-07-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_alter_topico_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
