# Generated by Django 5.0.7 on 2024-07-29 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_colaborador_is_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostalider',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_lider', to=settings.AUTH_USER_MODEL),
        ),
    ]
