# Generated by Django 5.0.7 on 2024-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_avaliacao_data_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='respostas',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pergunta_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pergunta_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
