# Generated by Django 5.0.7 on 2024-07-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0006_remove_avaliacaolider_avaliacao_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
    ]
