# Generated by Django 5.0.7 on 2024-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0006_avaliacao_pergunta_10_avaliacao_pergunta_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pergunta_27',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
