# Generated by Django 5.0.7 on 2024-07-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0007_remove_avaliacao_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliador_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
