# Generated by Django 5.0.7 on 2024-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0008_avaliacao_pergunta_29_avaliacao_pergunta_30_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pergunta_28',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
