# Generated by Django 5.0.7 on 2024-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0009_avaliacao_pergunta_28'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='alinhamento_semestral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='metas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pdi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pontos_melhoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
