# Generated by Django 5.0.7 on 2024-07-30 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0009_remove_avaliacao_avaliador_id_pergunta_competencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='area',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='cargo_atual',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='periodo_referencia',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='colaborador_avaliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
