# Generated by Django 5.0.7 on 2024-07-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0011_avaliacaoperguntaresposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaoperguntaresposta',
            options={'verbose_name': 'Avaliação Pergunta Resposta', 'verbose_name_plural': 'Avaliações Perguntas Respostas'},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoperguntaresposta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='avaliacaoperguntaresposta',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colab.avaliacao'),
        ),
        migrations.AlterField(
            model_name='avaliacaoperguntaresposta',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='avaliacaoperguntaresposta',
            table='avaliacao_pergunta_resposta',
        ),
    ]
