# Generated by Django 5.0.7 on 2024-07-31 12:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0012_alter_avaliacaoperguntaresposta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaolider',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='avaliacaolider',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaolider',
            name='competencias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaolider',
            name='compromissos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaolider',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='avaliacaolider',
            name='integracao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaolider',
            name='alinhamento_semestral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaolider',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_realizadas_lider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacaolider',
            name='colaborador_avaliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas_lider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacaolider',
            name='metas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoperguntaresposta',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoLiderPerguntaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colab.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colab.pergunta')),
            ],
            options={
                'verbose_name': 'Avaliação Líder Pergunta Resposta',
                'verbose_name_plural': 'Avaliações Líder Pergunta Resposta',
                'db_table': 'avaliacao_lider_pergunta_resposta',
            },
        ),
    ]
