# Generated by Django 5.0.7 on 2024-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0012_avaliacao_pergunta_1_avaliacao_pergunta_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_19',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_21',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_23',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_26',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_27',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_28',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_29',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_31',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_32',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_33',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_35',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_36',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_37',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
