# Generated by Django 5.0.7 on 2024-07-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0013_remove_avaliacaolider_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='competencias',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='compromissos',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='integracao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='texto',
        ),
        migrations.DeleteModel(
            name='AvaliacaoLiderPerguntaResposta',
        ),
    ]
