# Generated by Django 5.0.7 on 2024-07-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0014_remove_avaliacao_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='alinhamento_semestral',
        ),
    ]
